[package]
name = "dateorgimgs"
version = "0.1.0"
authors = ["sebas"]

[dependencies]
anyhow = "1.0"
chrono = "0.4.6"
clap = "2.23.2"
lazy_static = "1.4.0"
minidom = "0.13.0"
rayon = "1.0"
regex = "1.5.4"
rexiv2 = "0.7.0"
